### ISSUE TITLE
oss回调问题

### ISSUE THREAD

**Issue by Zhjwindrain** [qurenneng/spring-boot-integrate#1]
关于云存储，请问我想将用户上传文件的名字与类型存到数据库里，看到阿里云oss有回调的功能，但是看了您的代码，还不是太清楚如何将回调到云服务器上的数据，取出其中的文件名，文件类型。
我个人理解的是在类OssStsAuth的response方法中得到了回调的内容，但是不知道怎么取出我想要的数据，能将回调的数据直接入库，希望您能帮助我一下

**Comment by qurenneng** [comment]
这个在上传的时候就能获取到了啊，不需要等回调

**Comment by Zhjwindrain** [comment]
谢谢，已经解决了
